### ISSUE TITLE
MP4 Workflow 5 completes without audio

### ISSUE THREAD

**Issue by tjayz** [R3S3t9999/DoVi_Scripts#10]
Tried p5 ts with eac3 with atmos, results in video only. Manually demuxed and entered commands to mp4muxer to complete mp4 and worked thus file is not the problem is script. Tried same file replacing the object based audio with simple 2.0 aac and still result was file with  video only. Any settings I choose at top of script seem to not matter.

**Comment by R3S3t9999** [comment]
thanks. try next version.

**Comment by tjayz** [comment]
Had 15 files left to batch mux all went well with new version. Thanks
