### ISSUE TITLE
Feature Request: Add code to extract primary subtitle track as srt

### ISSUE THREAD

**Issue by tjayz** [R3S3t9999/DoVi_Scripts#11]
LG OLED's are dumb and cannot read sup/pgs. Their online support claims it can read sub but I failed at getting that to work as well, only srt works for my 2020 CX. 

At ~line 75 of script add a yes or no option to extract primary (based on persons language selected in script) subtitle to srt as a separate output to the video file itself, with name that matches the video ending in .srt. This could be run in conjunction with the extracting forced subtitles option, however, some movies have the primary subtitle as foreign language parts only.

Add [subtitledit](https://www.videohelp.com/download/SubtitleEdit-4.0.2.zip) portable version to tools folder which already has latest version of tesseract dictionary for english added to it and automatically add the demuxed sup to it. Window will pop up and user may manually review the subtitles and manually selects 'start ocr' and addresses any prompts if any, once ocr completes script takes over the rest. You have done something similar with manually edits of L5 in the script and extracting forced subtitles as well. 

Now our tv will have files that will allow subtitles to actually be viewed for the foreign language parts only rather than having a bunch of pgs subtitles that while enabled do absolutely nothing. Keeping the srt in same folder with the movie would allow jellyfin/emby etc etc to allow its selection when casting to tv. 

Would that be too much work?

**Comment by R3S3t9999** [comment]
yes, it should be doable.  thanks

**Comment by tjayz** [comment]
Thanks for putting this in. While I only tested one file so far, it exports all subtitles from all languages. I tried turning the setting to export all subs to no but had ill effect. Is there an option I am missing somewhere?

**Comment by R3S3t9999** [comment]
I'm confused.   Which workflow and which container do you use?

for example, in (1-1) container MKV or TS, only the subs according to your script language settings are exported/converted to SRT.
For the mp4 version, all the pgs subs are converted to srt.

**Comment by tjayz** [comment]
Test was mp4 workflow 5 just cause what I had available to test and is easiest workflow to get running will do more testing later with 1-1 later and report back

**Comment by R3S3t9999** [comment]
yes the mp4 version will mux all the subs/audio present in the input. The export function is for the TS and MKV version.

In this [non-official version](https://drive.google.com/file/d/1gi4wxZsQJ7Na8T2_OXRC8OHSmRNvDKuR/view?usp=sharing), it should be able to mux only the audio you want according to your script language settings if:
set mux_all_audio=NO
set mux_all_sub=NO

**Comment by tjayz** [comment]
Tested "The Revenant" workflow 5 mkv to ts and worked like a charm, did english only. 

One simple recommendation I would make for the file being uploaded to others on mega.nz, include tesseract v5 and make it be default ocr with tesseract v3 fallback enabled, the default built into subtitleedit often leaves spaces in the middle of words that ruins the viewing experience.

**Comment by R3S3t9999** [comment]
where can I download tesseract 5 ? I thought subtitle edit used it by default?

**Comment by tjayz** [comment]
![ocr screen](https://github.com/R3S3t9999/DoVi_Scripts/assets/90593277/0e361e2f-6bb3-448b-827b-74dc7636c5bc)
![ocrscreen2](https://github.com/R3S3t9999/DoVi_Scripts/assets/90593277/ce34e3e5-0288-4859-95b0-77b8f69b5243)

**Comment by R3S3t9999** [comment]
indeed the SRT quality is much better with version 5. Thank's for the info, I'll update the tool pack.
