### ISSUE TITLE
Fixed FPS in EDL_maker.py

### ISSUE THREAD

**Issue by filip11111** [R3S3t9999/DoVi_Scripts#15]
2-9 doesn´t work properly with video FPS other than 23.976, since the EDL_maker.py is always set to 23.976 FPS

**Comment by R3S3t9999** [comment]
Right, I forgot about that. 
Will fix it in the next version. Thanks

**Comment by filip11111** [comment]
It still doesn't work properly, unless I put e.g. "25FPS" to the mkv filename.

**Comment by R3S3t9999** [comment]
Strange, it worked with the 25fps mkv I tried.  Does your file mediainfo correctly report 25fps? Can you share a sample of your input please?

**Comment by filip11111** [comment]
https://we.tl/t-V9l0omXfxD
I believe the issue is that the script doesn't set %FPS% for some reason.

**Comment by R3S3t9999** [comment]
Ah, HDR10plus...
[this should work...](https://drive.google.com/file/d/128gq8aDUTKA_aT7SQsM9dkjA1EP1sosR/view?usp=sharing)

**Comment by filip11111** [comment]
Yes, now it works perfectly. Thank you!
