### ISSUE TITLE
Issue in converting DTDL.mp4 to STDL.mkv

### ISSUE THREAD

**Issue by deepakjoshiss** [R3S3t9999/DoVi_Scripts#18]
Hi, I found an issue while converting Profile 7 DTDL mp4 file to STDL mkv (Mode.7 - Workflow 2).
The converted file was still DTDL.

I think the issue is mkvmerge is not doing this by itself. I checked by removing the `:skip.BD` step and directly going to `:skipmkv` step (line 5839) and it worked correctly.

**Comment by R3S3t9999** [comment]
Hi,
I guess you meant 4-2 and not 7-2 but It looks like mkvtoolnix doesnt support DTDL MP4 to STDL... It also doesnt work if you mux the file directly without the script so there's nothing I can do about it.

It works from DT-DL TS/M2TS though.
