### ISSUE TITLE
workflow 6-2 with cropping not working at all

### ISSUE THREAD

**Issue by hyllm** [R3S3t9999/DoVi_Scripts#26]
workflow 6-2 with cropping not working at all.. no matter what i try. :(

```
Right border pixels offset...
0
Left border pixels offset...
0
Top border pixels offset...
280
Bottom border pixels offset...
280
LAV Splitter Source could not load video file.
Reading generate config file...
Parsing madVR measurement file...
Error: The system cannot find the file specified. (os error 2)
Press any key to continue . . .
```

**Comment by R3S3t9999** [comment]
it's working for me and many other people I know but some people have issues making it work and I don't why, sorry...

![Capture d’écran 2024-06-06 072122](https://github.com/R3S3t9999/DoVi_Scripts/assets/146230929/7518961c-7221-4df2-8538-075adf7205ca)

**Comment by hyllm** [comment]
can you please share lav filters version you use? maybe inćuding it in tools as portable woúd be solution... what paths? i have d:\ as outpu patch... dovi scripts are also on D:, MKV is on D also

**Comment by R3S3t9999** [comment]
I once tried to troubleshoot someone and couldn't find the reason why it didn't work and lavfilters settings were not the issue.

![Capture d’écran 2024-06-06 080719](https://github.com/R3S3t9999/DoVi_Scripts/assets/146230929/d7d6262a-2da7-4862-84cf-8549121edc93)

**Comment by hyllm** [comment]
can you try with this madVR version??? https://www.videohelp.com/download/madVRhdrMeasure205.zip

reverted back to 0.92.17 and working now. :)

**Comment by R3S3t9999** [comment]
Glad you figured it out but I'm not messing with the time-limited beta builds anymore. Once they expire, if you run 6-2, it breaks madMeasureHDR.exe, and the exe no longer works with any version.
