### ISSUE TITLE
Path 4-3 mkv single track dual layer to dual track dual layer audio out of sync

### ISSUE THREAD

**Issue by tjayz** [R3S3t9999/DoVi_Scripts#29]
I have a FraMeSToR download which is P7 ST DL which the x800m2 does not like to play, so wanted to preserve P7 and do DT DL but then the audio from the result is ~3 seconds out of sync. This can be by fixed by muxing the BL and EL with the audio from the original mkv but then you have substantial obsolete writes. I removed all subtitles from the mkv and reran the test and still same result. Only anomaly in the ffmpeg log was this:

 '[matroska,webm @ 0000016d67250d80] Invalid Block Addition value 0x0 for unknown Block Addition Mapping type 68766345, name "" '

Not sure if this is the source of issue or even if this error is reproducible on all P7 ST DLs but is causing problems on this set of files from FraMeSToR

**Comment by R3S3t9999** [comment]
Try disabling ffmpeg piping at line 190
set ffmpeg_pipe=NO

If it doesn't work, tell me which movie it is and I'll check it out

thanks

**Comment by tjayz** [comment]
Didn't resolve issue but did make the ffmpeg error go away.

Is Chernobyl 2019 TV series

**Comment by R3S3t9999** [comment]
I just tried Episode one and there is no sync issue so I don't know... I remuxed hundreds of ST P7 to DT TS with 4-3 in the past and never had sync issues...  Try to update your tsmuxer to the latest version, I think some recent versions had this problem

General
ID                                       : 0 (0x0)
Complete name                            : D:\SYNC\Chernobyl.S01E01.1.23.45.2160p.DTS-HD.MA.5.1.DV.HEVC.REMUX-FraMeSToR_DV.ts
Format                                   : MPEG-TS
File size                                : 25.1 GiB
Duration                                 : 58 min 54 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 61.1 Mb/s
Maximum Overall bit rate                 : 128 Mb/s
Frame rate                               : 23.976 FPS

Video #1
ID                                       : 4113 (0x1011)
Menu ID                                  : 1 (0x1)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : SMPTE ST 2086, HDR10 compatible
Codec ID                                 : 36
Duration                                 : 58 min 54 s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 996 cd/m2
Maximum Frame-Average Light Level        : 64 cd/m2

Video #2
ID                                       : 4117 (0x1015)
Menu ID                                  : 1 (0x1)
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@High
HDR format                               : Dolby Vision, Version 1.0, Profile 7.6, dvhe.07.06, EL+RPU, extended metadata compression, Blu-ray compatible / SMPTE ST 2086, Version HDR10, HDR10 compatible
Codec ID                                 : 6
Duration                                 : 58 min 54 s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0 (Type 2)
Bit depth                                : 10 bits
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : BT.2020
Mastering display luminance              : min: 0.0001 cd/m2, max: 1000 cd/m2

Audio
ID                                       : 4352 (0x1100)
Menu ID                                  : 1 (0x1)
Format                                   : DTS XLL
Format/Info                              : Digital Theater Systems
Commercial name                          : DTS-HD Master Audio
Muxing mode                              : Stream extension
Codec ID                                 : 134
Duration                                 : 58 min 54 s
Bit rate mode                            : Variable
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 93.750 FPS (512 SPF)
Bit depth                                : 24 bits
Compression mode                         : Lossless
Language                                 : English

Text #1
ID                                       : 4768 (0x12A0)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Delay relative to video                  : 15 s 682 ms
Language                                 : English

Text #2
ID                                       : 4769 (0x12A1)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Chinese

Text #3
ID                                       : 4770 (0x12A2)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Czech

Text #4
ID                                       : 4771 (0x12A3)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Danish

Text #5
ID                                       : 4772 (0x12A4)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Dutch

Text #6
ID                                       : 4773 (0x12A5)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Finnish

Text #7
ID                                       : 4774 (0x12A6)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : French

Text #8
ID                                       : 4775 (0x12A7)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : German

Text #9
ID                                       : 4776 (0x12A8)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Hungarian

Text #10
ID                                       : 4777 (0x12A9)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Korean

Text #11
ID                                       : 4778 (0x12AA)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Norwegian

Text #12
ID                                       : 4779 (0x12AB)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Polish

Text #13
ID                                       : 4780 (0x12AC)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Portuguese

Text #14
ID                                       : 4781 (0x12AD)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Romanian

Text #15
ID                                       : 4782 (0x12AE)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Spanish

Text #16
ID                                       : 4783 (0x12AF)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Spanish

Text #17
ID                                       : 4784 (0x12B0)
Menu ID                                  : 1 (0x1)
Format                                   : PGS
Codec ID                                 : 144
Language                                 : Swedish

**Comment by tjayz** [comment]
Must be a tool then or because I am using 2.0.7 version. Will update both later when have time and try again and see which is the culprit

**Comment by tjayz** [comment]
What nightly version of tsmuxer are you using?

**Comment by R3S3t9999** [comment]
https://github.com/justdan96/tsMuxer/releases/tag/nightly-2024-06-06-02-00-53

I know that recently, my script tools pack included [the problematic tsmuxer version](https://forum.doom9.org/showpost.php?p=2003493&postcount=423) so that might be it.

**Comment by tjayz** [comment]
Was txmuxer version as you stated. Solved.
