### ISSUE TITLE
Request to extract HDR10 metadata from input file

### ISSUE THREAD

**Issue by chrisdma** [R3S3t9999/DoVi_Scripts#3]
Hello,

I see there is an option to extract the DV metadata from a source file but do not see an option to extract HDR10/HDR10+ metadata from a provided file. Is this a feature you can possibly add?

My use case would be having two file sources, one SDR 2160p with a high bitrate and another HDR 2160p with a lower bitrate. I would like to export the HDR10/HDR10+ (depending on the source HDR file it can be either) metadata and inject it into the higher bitrate file. 

Thanks,
Chris

**Comment by R3S3t9999** [comment]
alright. The next version will output am HDR10+ JSON in the workflow (6-6).
if you don't want to wait,[ here's a  modified 1.9.5.5](https://drive.google.com/file/d/1n-XKChHvekKtHLMzKkHyQ0g4yDcv_zP8/view?usp=sharing)

**Comment by chrisdma** [comment]
> alright. The next version will output am HDR10+ JSON in the workflow (6-6).
> if you don't want to wait,[ here's a modified 1.9.5.5](https://drive.google.com/file/d/1n-XKChHvekKtHLMzKkHyQ0g4yDcv_zP8/view?usp=sharing)

Thanks for the quick reply! In the case that the source file is standard HDR and not HDR10, does this modified v1.9.5.5 work for that too?

**Comment by R3S3t9999** [comment]
for static HDR10, there is no metadata to export.

**Comment by chrisdma** [comment]
> for static HDR, there is no metadata to export.

I am a bit confused then, how would I get the HDR10 from the lower bitrate stream to the higher one, or is it baked into the video stream and this is not possible?

**Comment by R3S3t9999** [comment]
HDR10 has minimal and static metadata for the whole video. You can use freeware like [mediainfo](https://mediaarea.net/fr/MediaInfo) to find out that information. When you transcode an HDR10 video you just use the same static metadata in your x265 encoder parameters.

**Comment by chrisdma** [comment]
> HDR10 has minimal and static metadata for the whole video. You can use freeware like [mediainfo](https://mediaarea.net/fr/MediaInfo) to find out that information. When you transcode an HDR10 video you just use the same static metadata in your x265 encoder parameters.

If the SDR video is already a complete file (downloaded as is) as is the HDR10 file, is there a way to add that static metadata to the SDR file without transcoding and just multiplex/remux in that static metadata to not have to re-encode to keep the bitrate the same as is in that SDR file?

**Comment by R3S3t9999** [comment]
no not possible. SDR must be converted (and mapped) to HDR/REC2020

**Comment by chrisdma** [comment]
> no not possible. SDR must be converted (and mapped) to HDR/REC2020

I see, thank you for the information and I appreciate your HDR10+ version linked above! Cheers
