### ISSUE TITLE
mp4box muxing wrong parameters

### ISSUE THREAD

**Issue by kliffgomel** [R3S3t9999/DoVi_Scripts#30]
mp4box 2.5-DEV-rev461-ge2250d68f-ab-suite
default muxing cmd from script:
mp4box.exe  -add "c:\TMP\file.hevc":name=:hdr=none:dvp=8:fps=24000/1001p -tmp f:\TMP\temp.folder31_new\ -brand mp43isom -ab dby1 "c:\TMP\file.mp4"
With the default parameters I get an error:
Track Importing HEVC - Width 3840 Height 1600 FPS 24000/1001 SAR 1/1
HEVC Import results: 224256 samples (677559 NALUs) - Slices: 958 I 94104 P 129194 B - 1916 SEI - 958 IDR - 0 CRA
HEVC Stream uses forward prediction - stream CTS offset: 4 frames
**DV profile 8 must indicate a compatibility mode `hdr10`, `bt709` or `hlg2100`
Failure while setting DV profile: Bad Parameter** 

I think there is no need to use hdr=none

**Comment by R3S3t9999** [comment]
Hi, 
Yes I know, it was fixed in the latest BETA a couple of weeks ago

thanks
