### ISSUE TITLE
Typo in display message

### ISSUE THREAD

**Issue by FrostByteLXV** [R3S3t9999/DoVi_Scripts#39]
There is a minor typo in option 2.1 VERIFY_SYNC.  The word SCENE is misspelled as SCNENE inside the blue box.

v3.0.3 beta

![scnene](https://github.com/user-attachments/assets/cd3b9efb-679d-4e7a-82f5-76d146f6eb09)

**Comment by R3S3t9999** [comment]
thank you for reporting.
