### ISSUE TITLE
"Error - 2 input names specified, please check usage" - Lines 7688 and 7709 - Fix included

### ISSUE THREAD

**Issue by Crosis47** [R3S3t9999/DoVi_Scripts#47]
When running the new v3.0.3 release I get the error "Error - 2 input names specified, please check usage". I turned on echoes throughout the script and racked my brain for a while to find the source of this error. The issue appears to be the trailing "\\" on the temp folder path. If I copy the command from the console and run it after removing the trailing "\\", the command runs as expected. This appears to be a limitation in the way the new mp4box exe parses directory container paths.

Resultant command in script with echoes:
![image](https://github.com/user-attachments/assets/86a3da4f-beaf-4531-83b9-dbab0ea056ae)

Fixed command with "\\" removed.
![image](https://github.com/user-attachments/assets/40ad30d2-907a-4ba3-8684-b406d6ec3866)

As it does not seem to cause issue with anything but mp4box, I believe your easiest solution for this is to update lines 7688 and 7709 to use the below in place of %TEMP%.
**%TEMP:~0,-1%**

This will remove the trailing "\\" for mp4box without affecting any other code throughout the script. I have made this change to my copy of the script and it now runs through all processes as expected.

**Comment by R3S3t9999** [comment]
thanks, I'll check it out...

Not sure why it's using mp4box since your input doesn't have lossless audio or subtitles. It should only use the mp4muxer which is what it does on my end...

**Comment by R3S3t9999** [comment]
fixed in [BETA](https://drive.google.com/file/d/128gq8aDUTKA_aT7SQsM9dkjA1EP1sosR/view?usp=drive_link)
just rename to MP4

**Comment by Crosis47** [comment]
> Not sure why it's using mp4box since your input doesn't have lossless audio or subtitles. It should only use the mp4muxer which is what it does on my end... Do you have sample of your file? it shouldn't use mp4box at all..

M input actually has subtitles, I just have the script set not to mux them.

**Comment by Crosis47** [comment]
I know you closed this a while ago but I have a few questions regarding issues I am coming across related to your question that I only partially understand. So, as you pointed out here, it is using mp4box but it shouldn't be. I think this is because I have it set to OLD for the mp4muxer version. I have it this way because you call out that the NEW muxer does not work on some LG TVs. Is this only an issue with lossless audio/subs or is it an issue in general that you have seen?

This is all coming up because I am attempting to fix my Plex metadata and I just caught that Plex doesn't properly recognize HDR fallback on a file without the BL compat ID set to 1. In the past, the script settings were defaulted to using the NEW muxer because my older files have the ID set to 1. I don't have a 2018 LG TV to personally test this but some of my users may. I was hoping you could answer when the NEW muxer breaks LG TVs and I wouldn't have to test the different scenarios.

Here is my current [settings](https://pastebin.com/HcDW6sJA)

**Comment by R3S3t9999** [comment]
Here's the script logic...

OLD mode (for 2016-2018 LG TVs):
1- if the input has no SRT subtitles  and no lossless audio, mp4muxer will be used and the compatibility ID will be set correctly
2- If the input has SRT subtitles, or/and is set to convert pgs to srt, or/and the script is set to keep lossless audio, MP4box will be used and the old version I have to use for the mp4 to work on old TV will not put a combability ID
3- if the script is set to ''force mp4muxer'', mp4box will not be used regardless of the input tracks.

NEW mode:
1- By default the script will always use mp4box regardless of the input tracks so that mode will be a lot faster. New mp4box can also set a proper compatibility ID.
2- Can also be configured to force the newer mp4muxer but for some reason, it doesn't work on my Windows 11 PC but it works on my Windows 10 PC.
3- The new mp4box breaks 7.1 DDP audio


***** For the old and new modes. mp4box can sometimes fail to mux DDP Atmos track and SRT and DDP atmos can cause the video to stutter.

**Comment by Crosis47** [comment]
So, I've been trying to find the most compatible settings with my own devices (via Plex app) and after a ton of testing I've found:

OldMuxer:
Plays perfect on all LG devices
Plays perfect on Google devices
Will not load on Samsung devices

NewMuxer (any mp4box version):
Old LG devices will play but drops DoVi and cannot rewind or fast forward
New LG devices will play as DoVi but cannot fast forward or rewind
Plays perfect on Google devices
Plays perfect on Samsung sevices

TS files:
Plays perfect on all LG devices
Plays perfect on Samsung devices
Won't play at all on Google devices

MKV:
All LG devices will play but drops DoVi
Plays great on Samsung devices
Plays great on Google Devices

Have you or anyone else found a muxer that will create a file that plays correctly across these device types?

**Comment by R3S3t9999** [comment]
I really hate the MP4 container and IMO, the best is to install kodi on LG WEBOS and DV MKV will work (even profile 7 will work).

https://kodi.wiki/view/HOW-TO:Install_Kodi_for_webOS

**Comment by Crosis47** [comment]
You make a good point. To your knowledge, are there any devices that do have issues with MKVs? I know when I first started with my Plex server, MKV was not recommended, as MP4 was considered more compatible but I chose MKV for ease of use. That compatibility issue seems to have reversed over the years.

As of now, only my DoVi files are MP4 so about 10% of my collection needs to be remuxed to MKV. Your MKV mux workflow does batches, doessn't it?

If so, I haven't used it and have a question:

If I pick a folder that contains for instance:
Movie1.mp4
Movie1.en.srt
Movie2.mp4
Movie2.en.srt
Movie2.en.forced.srt

Will the script mux the matching files for each movie into 1 MKV?

**Comment by R3S3t9999** [comment]
Yeah, MKV is a much better container and i'm not aware of any issue.

The script can batch mux to MKV but no, it won't pick up external subs/audio. You could easily ask [chatgpt or claude](https://lmarena.ai/) to make you a script that can do that though.
