### ISSUE TITLE
[Feature Request] Add more than 2 input for screenshot comparisons

### ISSUE THREAD

**Issue by zdm9981** [R3S3t9999/DoVi_Scripts#48]
Currently I have to use 7,2 for source A + source B, then source A + source C since B, C have different delays.

Ideal workflow: input Source A, input source B, input delay, (Optional) input source C, input delay....

**Comment by R3S3t9999** [comment]
Added it in the [latest BETA](https://drive.google.com/file/d/128gq8aDUTKA_aT7SQsM9dkjA1EP1sosR/view?usp=drive_link).
 I did not have time to test it yet so let me know if there are issues.
