### ISSUE TITLE
[Feature Request] Batch files ability for 4-3

### ISSUE THREAD

**Issue by ceedveed** [R3S3t9999/DoVi_Scripts#50]
I use Sony X800M2. In order to avoid the ST DL bug, I convert all my ST DL rips to DT DL by using workflow 4-3. Unfortunately, this means a manual process of selecting 4-3 for every show in a TV series.

Is it possible to do this in a batch file way?

**Comment by R3S3t9999** [comment]
Yes, I can do that. :)

**Comment by R3S3t9999** [comment]
Please try the latest [BETA](https://drive.google.com/file/d/128gq8aDUTKA_aT7SQsM9dkjA1EP1sosR/view?usp=drive_link)

input can be a single file or a folder with files. The script expects the files in your folder to be Profile7 ST-DL.

**Comment by ceedveed** [comment]
I tried the 3.0.5 Beta and changed the name of the linked file to DoVi_Scripts_TS.bat. Thanks for understanding that I needed TS files due to X800M2 use even though I didn't explicitly mention I needed TS.

Batch file function works for workflow 4-3. Thank you!

**Comment by ceedveed** [comment]
I'm not sure if this is related to the new ability to batch in the 4-3 workflow. But I found a bug.

- Run 4-3 flow with a single file (movie A)
- When completed, do not quit, instead go back to main menu.
- Run 4-3 flow with a single file (movie B)
- The created file is movie A again. Looking at the logs also shows movie A being processed.

I re-did the above steps, except with quitting then running the .bat file again. It worked fine.

**Comment by R3S3t9999** [comment]
yeah, that function might not work in all the workflows. I never use it and I have to look whats wrong one day...
It's better to just close the window and start a new job.
