### ISSUE TITLE
tools\ missing in path to avs2pipe_path

### ISSUE THREAD

**Issue by M0djO** [R3S3t9999/DoVi_Scripts#7]
The path to the avs2pipe_path is wrong in v1.9.8.

set avs2pipe_path=%~dp0avs2pipemod64.exe

should be

set avs2pipe_path=%~dp0tools\avs2pipemod64.exe

**Comment by R3S3t9999** [comment]
oh, you're right. I just copied the path from the external file.
thanks for letting me know.
