### ISSUE TITLE
downscale is set twice at the beginning of the script, to different values

### ISSUE THREAD

**Issue by M0djO** [R3S3t9999/DoVi_Scripts#8]
In v1.9.8, in the config part of the script downscale is set twice on different locations (line numbers in front of each line), and its set to different value.

The behavior for me is that it doesn't downscale, so does that mean its the first value that is applied then?

104  ::choose if you want 8-6-1 to downscale to 1080p (default = NO)
105  set downscale=NO

and

120  ::choose if you want 8-6-1 to downscale to 1080p (default = NO)
121  set downscale=YES

**Comment by R3S3t9999** [comment]
oops... my bad. line120-121 should be deleted

that option is only for the workflow that delivers the 100nits trim pass which is now (8-6-4) but was 8-6-1 before. I should update the comments in the script since a lot changed since I wrote them. 

thanks.
